import {hasAccess,gate,recordProgress,accountSnapshot,placeTrade,canSubmitTrade} from './platform.js';
import {create,PAIRS,label,RULES,submit,cancel,close,demoTick,tick,stats,result,estimate,quote} from './packages/simulation-core/index.js';
const $=id=>document.getElementById(id),key='aces-practice-lab-v5',fmt=(v,d=2)=>Number(v).toLocaleString('en-US',{minimumFractionDigits:d,maximumFractionDigits:d}),px=(v,p=pair)=>fmt(v,p.endsWith('USDT')?2:6),escape=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let s=create(),pair='BTCUSDT',tab='positions',candles={},generation=0,busy=false,feedError='',requestedMode=null,storageOK=true;
try{const stored=JSON.parse(localStorage.getItem(key));if(stored?.state?.version===1&&['demo','live'].includes(stored.state.mode)&&Number.isFinite(stored.state.cash)&&Array.isArray(stored.state.positions)&&Array.isArray(stored.state.orders)&&Array.isArray(stored.state.closed)){s=stored.state;candles=stored.candles||{};pair=PAIRS.includes(stored.pair)?stored.pair:pair;}}catch{storageOK=false;}
s.sessionId ||= crypto.randomUUID();
$('source').value=s.mode;
function save(){for(const p of s.closed)if(p.note?.trim())recordProgress(s.sessionId+":"+p.id,p.closedAt);try{localStorage.setItem(key,JSON.stringify({state:s,candles,pair}));storageOK=true;}catch{storageOK=false;}$('save-status').textContent=storageOK?'Saved on this device':'Storage unavailable · export to keep your journal';}
let messageTimer;function tell(message){$('message').textContent=message;$('message').style.display='block';clearTimeout(messageTimer);messageTimer=setTimeout(()=>$('message').style.display='none',6000);}
const intervalMs=()=>({'1m':60000,'5m':300000,'15m':900000,'1h':3600000})[$('interval').value];
function candleTick(quotes,at){for(const [id,price] of Object.entries(quotes)){const k=id+':'+$('interval').value;const rows=candles[k]??=[];const bucket=Math.floor(at/intervalMs())*intervalMs();let row=rows.at(-1);if(!row||row.t!==bucket){rows.push({t:bucket,o:price,h:price,l:price,c:price});if(rows.length>100)rows.shift();}else{row.c=price;row.h=Math.max(row.h,price);row.l=Math.min(row.l,price);}}}
function seedChart(){if(s.mode!=='demo')return;const temp=create(),tf=intervalMs(),end=Math.floor(Date.now()/tf)*tf;for(let i=79;i>=0;i--){const q=demoTick(temp,end-i*tf);candleTick(q,end-i*tf);} // fictional, separate from account execution
 for(const id of PAIRS){const rows=candles[id+':'+$('interval').value];if(s.quotes[id]){const row=rows.at(-1);row.c=s.quotes[id].price;row.h=Math.max(row.h,row.c);row.l=Math.min(row.l,row.c);}}
}
async function json(url){const response=await fetch(url,{signal:AbortSignal.timeout(8000)});if(!response.ok)throw Error('Feed unavailable ('+response.status+'). Trading waits for fresh prices.');return response.json();}
async function history(){if(s.mode!=='live'){seedChart();draw();return;}const gen=generation,id=pair,tf=$('interval').value;try{const rows=await json('https://data-api.binance.vision/api/v3/klines?symbol='+id+'&interval='+tf+'&limit=80');if(gen!==generation||!Array.isArray(rows))return;candles[id+':'+tf]=rows.filter(c=>[0,1,2,3,4].every(i=>Number.isFinite(+c[i]))).map(c=>({t:+c[0],o:+c[1],h:+c[2],l:+c[3],c:+c[4]}));draw();}catch{if(gen===generation){$('chart-info').textContent='Candle history unavailable · quotes may still be available';}}}
async function refresh(){if(busy||!hasAccess())return;busy=true;const gen=generation;try{if(s.mode==='demo'){const now=Date.now();const q=demoTick(s,now);candleTick(q,now);feedError='';}else{const q={},results=await Promise.allSettled(PAIRS.map(async id=>{const d=await json('https://data-api.binance.vision/api/v3/ticker/price?symbol='+id);if(d.symbol===id&&Number.isFinite(+d.price)&&+d.price>0)return [id,+d.price];throw Error('Invalid quote');}));if(gen!==generation)return;for(const r of results)if(r.status==='fulfilled')q[r.value[0]]=r.value[1];const now=Date.now();tick(s,q,now);candleTick(q,now);feedError=Object.keys(q).length<PAIRS.length?'Some pairs unavailable · only fresh quotes can trade':'';}save();render();}catch(e){if(gen===generation){feedError=e.message;render();}}finally{busy=false;}}
function order(){return {pair,side:$('side').value,type:$('type').value,size:Number($('size').value),lev:Number($('leverage').value),trigger:Number($('trigger').value),sl:$('sl').value===''?null:Number($('sl').value),tp:$('tp').value===''?null:Number($('tp').value),note:$('note').value};}
function preview(){const o=order(),mark=s.quotes[pair]?.price;const e=estimate(o,o.type==='market'?mark:o.trigger);$('trigger-row').hidden=o.type==='market';$('estimate').innerHTML=`<div><span>Exposure</span><b>${fmt(e.notional)} PTS</b></div><div><span>Entry fee</span><b>${fmt(e.fee)} PTS</b></div><div><span>Planned stop loss*</span><b class="${e.risk===null?'down':''}">${e.risk===null?'No stop set':fmt(e.risk)+' PTS'}</b></div><small>*Estimate includes both fees. Gaps may lose more.</small>`;let fresh=true;try{quote(s,pair,Date.now());}catch{fresh=false;}$('submit').disabled=!fresh||!canSubmitTrade();$('submit').textContent=canSubmitTrade()?'Place paper order · 10 ACPH':'Need 10 ACPH for a new order';}
function render(){const m=stats(s);$('equity').textContent=fmt(m.equity);$('return').textContent=fmt(m.returnPct)+'%';$('return').className=m.equity>=10000?'up':'down';$('cash').textContent=fmt(s.cash)+' PTS available';$('dd').textContent=fmt(m.drawdown*100)+'%';$('count').textContent=m.n;$('winrate').textContent=m.n?fmt(m.winRate*100,1)+'% wins · net of fees':'Win rate needs closed trades';$('pair-title').textContent=label(pair);$('price').textContent=s.quotes[pair]?px(s.quotes[pair].price):'—';
 $('markets').innerHTML=PAIRS.map(id=>`<button class="market ${id===pair?'active':''}" data-pair="${id}"><span>${label(id)}<small>${id.endsWith('USDT')?'USDT quoted':'Relative performance'}</small></span><strong>${s.quotes[id]?px(s.quotes[id].price,id):'—'}</strong></button>`).join('');
 const age=s.quotes[pair]?Math.max(0,Math.floor((Date.now()-s.quotes[pair].at)/1000)):null;const fresh=age!==null&&age<15;$('feed').textContent=(s.mode==='demo'?'FICTIONAL · seeded practice':'BINANCE · polled live quotes')+' · '+(age===null?'waiting':age+'s old')+(fresh?'':' · execution paused')+(feedError?' · '+feedError:'');$('feed').style.color=fresh?'var(--green)':'var(--red)';$('chart-info').textContent=s.mode==='demo'?'Fictional candles · seed 42':'Binance OHLC · '+$('interval').value+' buckets';
 $('position-count').textContent=s.positions.length;$('order-count').textContent=s.orders.length;$('journal-count').textContent=s.closed.length;records();preview();draw();
 let coaching=m.n===0?'Write a reason before entering, then review the result after costs. A stop is a plan, not a guaranteed fill.':m.expectancy<0?'Your average closed trade loses points after costs. Inspect the journal for oversized losses and repeated entries before increasing risk.':'Your average closed trade is positive in this session. Test the same rules across more dates and market conditions before drawing conclusions.';if(s.positions.length>m.protected)coaching+=' '+(s.positions.length-m.protected)+' open position(s) have no stop loss.';
 $('review').innerHTML=`<div class="metric"><span>Expectancy / trade</span><b>${m.expectancy===null?'—':fmt(m.expectancy)+' PTS'}</b></div><div class="metric"><span>Profit factor</span><b>${m.profitFactor===null?'—':fmt(m.profitFactor)}</b></div><div class="metric"><span>Fees charged</span><b>${fmt(m.fees)} PTS</b></div><p>${coaching}</p><p class="muted">${m.n<30?'Early sample · fewer than 30 closed trades.':'Sample accumulated · quantity alone does not prove an edge.'} Profit factor needs at least one losing trade.</p>`;
}
function records(){const rows=tab==='positions'?s.positions:tab==='orders'?s.orders:[...s.closed].reverse();if(!rows.length){$('records').innerHTML='<div class="empty">'+({positions:'No open positions.<br>Plan an entry with the order ticket.',orders:'No pending orders.<br>Limit and stop entries wait for a matching fresh quote.',journal:'Your journal starts with the first closed trade.<br>Every result includes entry and exit costs.'})[tab]+'</div>';return;}
 let headings=tab==='positions'?['Pair / side','Margin','Entry','Net P&L*','SL / TP','Action']:tab==='orders'?['Pair / side','Reserved PTS','Type','Trigger','Thesis','Action']:['Pair / side','Net P&L','Fees','Exit reason','Thesis','Closed'];
 const body=rows.map(p=>{const name=`${label(p.pair)}<small class="muted"> ${p.side} ${p.lev}×</small>`;if(tab==='positions'){const r=result(p,s.quotes[p.pair]?.price??p.entry);return `<tr><td>${name}</td><td>${fmt(p.size)}</td><td>${px(p.entry,p.pair)}</td><td class="${r.net>=0?'up':'down'}">${fmt(r.net)}</td><td>${p.sl?px(p.sl,p.pair):'—'} / ${p.tp?px(p.tp,p.pair):'—'}</td><td><button data-close="${p.id}">Close</button></td></tr>`;}if(tab==='orders')return `<tr><td>${name}</td><td>${fmt(p.size+p.entryFee)}</td><td>${p.type}</td><td>${px(p.trigger,p.pair)}</td><td class="journal-note">${escape(p.note)||'—'}</td><td><button data-cancel="${p.id}">Cancel</button></td></tr>`;return `<tr><td>${name}</td><td class="${p.net>=0?'up':'down'}">${fmt(p.net)}</td><td>${fmt(p.entryFee+p.exitFee)}</td><td>${escape(p.reason)}</td><td class="journal-note">${escape(p.note)||'—'}</td><td>${new Date(p.closedAt).toLocaleString()}</td></tr>`;}).join('');$('records').innerHTML='<table><thead><tr>'+headings.map(t=>'<th>'+t+'</th>').join('')+'</tr></thead><tbody>'+body+'</tbody></table>'+(tab==='positions'?'<p class="fine" style="padding:12px 16px">*Estimated net result includes both fees and exit slippage.</p>':'');}
function draw(){const el=$('chart'),w=el.clientWidth,h=el.clientHeight,dpr=devicePixelRatio||1;el.width=w*dpr;el.height=h*dpr;const ctx=el.getContext('2d');ctx.scale(dpr,dpr);ctx.clearRect(0,0,w,h);const rows=(candles[pair+':'+$('interval').value]||[]).slice(-80);if(!rows.length){ctx.fillStyle='#98a8ba';ctx.font='14px system-ui';ctx.fillText('Waiting for price history…',22,h/2);return;}const hi=Math.max(...rows.map(r=>r.h)),lo=Math.min(...rows.map(r=>r.l)),pad=(hi-lo)*.1||hi*.002,min=lo-pad,max=hi+pad,left=18,right=82,top=18,bottom=28,cw=w-left-right,ch=h-top-bottom,y=v=>top+(max-v)/(max-min)*ch;ctx.font='11px monospace';for(let i=0;i<5;i++){const value=min+(max-min)*i/4,yy=y(value);ctx.strokeStyle='#26323f';ctx.beginPath();ctx.moveTo(left,yy);ctx.lineTo(w-right,yy);ctx.stroke();ctx.fillStyle='#98a8ba';ctx.fillText(px(value),w-right+8,yy+4);}const step=cw/Math.max(rows.length,25),bw=Math.max(2,step*.6);rows.forEach((r,i)=>{const x=left+(i+.5)*step;ctx.strokeStyle=ctx.fillStyle=r.c>=r.o?'#5cddbb':'#ff8191';ctx.beginPath();ctx.moveTo(x,y(r.h));ctx.lineTo(x,y(r.l));ctx.stroke();ctx.fillRect(x-bw/2,Math.min(y(r.o),y(r.c)),bw,Math.max(1,Math.abs(y(r.o)-y(r.c))));});if($('ema').checked&&rows.length>=20){let avg=rows.slice(0,20).reduce((a,r)=>a+r.c,0)/20;ctx.strokeStyle='#ffab49';ctx.lineWidth=1.5;ctx.beginPath();ctx.moveTo(left+19.5*step,y(avg));for(let i=20;i<rows.length;i++){avg=rows[i].c*2/21+avg*19/21;ctx.lineTo(left+(i+.5)*step,y(avg));}ctx.stroke();}ctx.fillStyle='#98a8ba';ctx.fillText(new Date(rows[0].t).toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'}),left,h-8);ctx.fillText(new Date(rows.at(-1).t).toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'}),Math.max(left,cw-35),h-8);}
$('order-form').addEventListener('input',preview);$('order-form').addEventListener('submit',e=>{e.preventDefault();if(!hasAccess()){gate();return;}try{const id=placeTrade(s,order(),Date.now(),crypto.randomUUID());save();render();tell('Paper order #'+id+($('type').value==='market'?' opened.':' queued. Points reserved until fill or cancellation.'));}catch(e){tell(e.message);}});
$('markets').addEventListener('click',e=>{const b=e.target.closest('[data-pair]');if(b){pair=b.dataset.pair;for(const id of ['sl','tp','trigger'])$(id).value='';render();history();save();}});
document.querySelector('.tabs').addEventListener('click',e=>{const b=e.target.closest('[data-tab]');if(b){tab=b.dataset.tab;document.querySelectorAll('[data-tab]').forEach(x=>x.classList.toggle('active',x===b));records();}});
$('records').addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;try{if(b.dataset.close)close(s,Number(b.dataset.close),Date.now());else if(b.dataset.cancel)cancel(s,Number(b.dataset.cancel));save();render();tell('Session updated.');}catch(e){tell(e.message);}});
$('interval').addEventListener('change',()=>{history();draw();});$('ema').addEventListener('change',draw);$('refresh').addEventListener('click',()=>{refresh();history();});window.addEventListener('resize',draw);
function requestReset(mode){requestedMode=mode;$('confirm').showModal();}$('source').addEventListener('change',()=>{const mode=$('source').value;$('source').value=s.mode;requestReset(mode);});$('reset').addEventListener('click',()=>requestReset(s.mode));$('keep').addEventListener('click',()=>$('confirm').close());$('new').addEventListener('click',()=>{generation++;s=create(requestedMode);s.sessionId=crypto.randomUUID();candles={};$('source').value=s.mode;feedError='';$('confirm').close();for(const id of ['sl','tp','trigger','note'])$(id).value='';save();render();history();refresh();});
$('export').addEventListener('click',()=>{const blob=new Blob([JSON.stringify({exportedAt:new Date().toISOString(),rules:RULES,platform:accountSnapshot(),model:'Isolated paper contracts; no funding/depth; browser-local; not verified',state:s},null,2)],{type:'application/json'});const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='aces-practice-journal-'+new Date().toISOString().slice(0,10)+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);});
window.addEventListener('aces-access',e=>{if(e.detail.first){generation++;s=create();s.sessionId=crypto.randomUUID();candles={};$('source').value=s.mode;}save();render();history();refresh();});
$('export-existing').addEventListener('click',()=>$('export').click());
gate();
if(s.mode==='demo'&&!s.quotes.BTCUSDT)demoTick(s,Date.now());render();history();refresh();setInterval(refresh,5000);setInterval(()=>{preview();const q=s.quotes[pair];if(q&&Date.now()-q.at>15000){$('feed').textContent='STALE · execution paused · waiting for fresh '+label(pair)+' quotes';$('feed').style.color='var(--red)';}},1000);
