(() => {
'use strict';
const active=location.pathname;
if(!['/','/index.html','/philosophy/','/journal/'].includes(active)){const missionModule=document.createElement('script');missionModule.type='module';missionModule.src='/shared/mission-workspace.js';document.head.append(missionModule);}
document.getElementById('site-header').innerHTML=`<header class="masthead"><a class="wordmark" href="/" aria-label="BTCisGTO home"><span class="coin-mark">₿</span>BTC<span>is</span>GTO<span class="wordmark-dot">.</span></a><button class="nav-toggle" aria-controls="site-nav" aria-expanded="false">Menu <span aria-hidden="true">☰</span></button><nav id="site-nav" aria-label="Main navigation"><a href="/workflow/">Mission control</a><details class="tools-menu"><summary>Tools <span aria-hidden="true">⌄</span></summary><div class="tools-popover"><a href="/dashboard/"><strong>Bitcoin Dashboard ↗</strong><small>Market & network data</small></a><a href="/tradingtool/"><strong>Trading Sim ↗</strong><small>Practice with paper points</small></a><a href="/edge/"><strong>Edge Tool ↗</strong><small>Research preview · access key</small></a><a href="/agents/"><strong>Trading Agents</strong><small>Train, test & review</small></a><a href="/tools/">Explore all tools →</a></div></details><a href="/treasury/">Treasury</a><a href="/journal/">Journal</a><a href="/philosophy/">Philosophy</a><a class="nav-mission" href="/mission/">The mission ↗</a></nav></header>`;
document.getElementById('site-footer').innerHTML=`<footer class="global-footer shell"><div class="footer-main"><div><a class="wordmark" href="/">BTC<span>is</span>GTO<span class="wordmark-dot">.</span></a><p>Bitcoin. Truth. Compassion.<br>One hand at a time.</p></div><div><strong>Use the tools</strong><a href="/dashboard/">Dashboard ↗</a><a href="/tradingtool/">Trading Sim ↗</a><a href="/edge/">Edge Tool ↗</a><a href="/agents/">Trading Agents</a></div><div><strong>Follow the work</strong><a href="/treasury/">Treasury & evidence</a><a href="/journal/">Build journal</a><a href="/philosophy/">Philosophy</a><a href="/sitemap/">Site map</a></div><div><strong>The road to HOME</strong><a href="/mission/">LOLA’s HOME</a><a href="/about/">Jay’s story ↗</a><a href="mailto:hello@btcisgto.cloud">Get in touch ↗</a><a href="https://x.com/btcisgto" target="_blank" rel="noopener noreferrer">Follow on X ↗</a></div></div><div class="footer-legal"><span>© 2026 BTCisGTO · Angeles City, Philippines</span><span>Practice & research. No investment subscription or guaranteed returns.</span></div></footer>`;
const nav=document.getElementById('site-nav'),toggle=document.querySelector('.nav-toggle'),toolsMenu=document.querySelector('.tools-menu');
function closeMenu(){nav.classList.remove('is-open');toggle.setAttribute('aria-expanded','false');toolsMenu.open=false;}
toggle.addEventListener('click',()=>{const open=toggle.getAttribute('aria-expanded')!=='true';toggle.setAttribute('aria-expanded',String(open));nav.classList.toggle('is-open',open);});
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&(nav.classList.contains('is-open')||toolsMenu.open)){const hadOpen=nav.classList.contains('is-open');closeMenu();if(hadOpen)toggle.focus();else document.querySelector('.tools-menu summary').focus();}});
document.addEventListener('click',e=>{if(!toolsMenu.contains(e.target))toolsMenu.open=false;});
nav.querySelectorAll('a').forEach(a=>{if(new URL(a.href).origin===location.origin&&new URL(a.href).pathname===active)a.setAttribute('aria-current','page');a.addEventListener('click',closeMenu);});

})();

